#!/bin/sh
# prerm script for contrast-finder-webapp
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

echo "-----------------------------------"
echo "----> prerm script for contrast-finder-webapp"
case "$1" in
  remove|upgrade|deconfigure)
    echo "----> nothing to do for \`$1'"
  ;;

  failed-upgrade)
    echo "----> nothing to do for \`$1'"
  ;;

  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac
echo "-----------------------------------"


exit 0
