#!/bin/sh
# postinst script for contrast-finder-webapp
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

echo "-----------------------------------"
echo "----> postinst script for contrast-finder-webapp"
case "$1" in

  configure)
    echo "----> nothing to do for \`$1'" 
    echo ""
    echo "default URL: "
    echo "http://localhost:8080/contrast-finder/"
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    echo "----> nothing to do for \`$1'" 
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac
echo "-----------------------------------"


exit 0
