#!/bin/sh
# postrm script for contrast-finder-webapp
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

echo "-----------------------------------"
echo "----> postrm script for contrast-finder-webapp"
case "$1" in
  purge)
    echo "----> nothing to do for \`$1'"
  ;;

  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    echo "----> nothing to do for \`$1'"
  ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac
echo "-----------------------------------"


exit 0
